### PR TITLE
Create delete_cluster.sh

### PR DESCRIPTION
**Pull request by rasekar2000**
Having this delete cluster file will help to delete the created components !!

### CODE REVIEW

**Comment by rasekar2000** [comment]
Please merge this change !!

**Comment by rimusz** [comment]
thanks for the PR, please L11 has `# create servers` it should `# delete servers`.
also some confirmation prompt would be good there, just in case somebody deletes the clusters by mistake

**Comment by rasekar2000** [comment]
Sure !! Will fix that.

I see that the confirmation prompt is available by default.

Disabling confirmation can be implemented by
 export CLOUDSDK_CORE_DISABLE_PROMPTS=1
 (or)  --usage-reporting false
http://stackoverflow.com/questions/31553059/automatically-select-prompt-using-linux-sh-script

When I am done, I will update with a new PR.

**Comment by rasekar2000** [comment]
Alright : PR is updated with L11 change. Please merge , when you get a chance!

**Comment by rimusz** [comment]
👍

**Pull request merged**
